# Generated by Django 5.0.6 on 2024-06-03 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ap_pat', models.CharField(max_length=80)),
                ('ap_mat', models.CharField(max_length=80)),
                ('usu', models.CharField(max_length=80)),
                ('passw', models.CharField(max_length=80)),
                ('fecha_nac', models.DateField()),
                ('status', models.SmallIntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carreras.carreras')),
            ],
        ),
    ]
